GPS driver integration
Matt-Lemcke/digital-dozenal-clock pull request #53
Opened 2023-11-27 03:40 UTC by DanielHernandez-0801

2023-11-27 16:15 UTC, Matt-Lemcke requested changes
Just a few comments to look at. Did you update the .ioc file with the changes?

2023-11-27 16:15 UTC, Matt-Lemcke commented on firmware/src/gps.c
> +    curr_time_ms = gpsTimeToMs(Gps_GetTime(self));
Would it make more sense to check the connection flag before attempting to read the time?

2023-11-27 16:15 UTC, Matt-Lemcke commented on firmware/src/gps.c
> +    GpsTime t;
Probably won't be a big deal for us, but we could make t and utc_time global static variables to save on RAM. Up to you if you want to fix this

2023-11-27 16:15 UTC, Matt-Lemcke commented on firmware/src/gps.c
> +    t.hr = t.hr + self->timezone_offset;
Seems like there could be problems here. Example: t.hr = 23 and offset is 5 would mean t.hr becomes 28. Same if t.hr = 1 and offset is -4 would mean t.hr becomes 252 (unsigned int)

2023-11-27 16:15 UTC, Matt-Lemcke commented on firmware/src/gps.c
> +    return CLOCK_OK;
Maybe add some value checking here and reject values above/below max/min offsets

2023-11-27 16:15 UTC, Matt-Lemcke commented on firmware/stm32f4_disc/Core/Inc/uart-gps.h
> +#define	GPS_USART	&huart4
Could we change this so we can choose which uart handler to use? We could do something like i2c-rtc.c where the handler is passed into the Init function

2023-11-27 22:54 UTC, DanielHernandez-0801 commented
> Just a few comments to look at. Did you update the .ioc file with the changes?

2023-11-28 00:50 UTC, Matt-Lemcke reviewed
Looks good. Just a couple more things before it's ready for testing

2023-11-28 00:50 UTC, Matt-Lemcke commented on firmware/src/gps.c
> +    }
An equivalent way of writing the hour calculation is gps_time.hr = (24 + utc_hr - offset) % 24. I tried it out and it seems to work well in all the boundary scenarios. Whatever you prefer

2023-11-28 00:50 UTC, Matt-Lemcke commented on firmware/src/gps.c
> +    int8_t hr = ((uint8_t) utc_time / 10000) + self->timezone_offset;
What is the time unit for utc_time? Based on your calculations it doesn't look like seconds or milliseconds

2023-11-29 21:30 UTC, DanielHernandez-0801 commented on firmware/src/gps.c
> +    int8_t hr = ((uint8_t) utc_time / 10000) + self->timezone_offset;
They give the hour, min and seconds as separate digits of the utc time float. For example:

utc_time = 071325.21
hr = 07
min = 13
sec = 25.21

This is why I'm just extracting these digits using integer division and modulo operator. Like so:

utc_time = 071325.21
hr = utc_time / 10000 = 07
min = (utc_time % 10000) / 100 = (1325.21) / 100 = 13
sec = utc_time % 100 = 25.21

2023-11-30 19:02 UTC, Matt-Lemcke commented on firmware/src/gps.c
> +    int8_t hr = ((uint8_t) utc_time / 10000) + self->timezone_offset;
Ah ok that makes more sense now lol

2023-11-30 19:03 UTC, Matt-Lemcke approved these changes
Ready to merge once we have tested with hardware

2024-06-06 22:38 UTC, merged